import { SignInButton } from "@clerk/clerk-react";
import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";
import Loader from "~/components/loader";

dayjs.extend(relativeTime);

const Feed = () => {
  const { data, isLoading: isPostsLoading } = api.post.getAll.useQuery();

  if (isPostsLoading)
    return (
      <div className="grid min-h-screen place-items-center">
        <Loader size={100} />
      </div>
    );

  if (!data) return <div>Something went wrong...</div>;

  return (
    <div className="flex-column flex">
      {data.map((post) => (
        <PostView {...post} key={post.post.id} />
      ))}
    </div>
  );
};

const CreatePostWizard = () => {
  const { user, isLoaded: isUserLoaded } = useUser();

  if (!isUserLoaded)
    return (
      <div className="grid place-items-center">
        Fetching user data...
        <Loader size={16} />
      </div>
    );

  if (!user)
    return (
      <div className="grid place-items-center">Something went wrong...</div>
    );

  return (
    <>
      <div className="flex h-full w-full items-center gap-2">
        <Image
          className="h-14 w-14 rounded-full"
          src={user.profileImageUrl}
          alt="My profile Image"
          width={56}
          height={56}
          priority
        />
        <input
          placeholder="Share your thoughts..."
          className="grow bg-transparent outline-none"
          name="post"
        />
      </div>
    </>
  );
};

type postWithUser = RouterOutputs["post"]["getAll"][number];
const PostView = (props: postWithUser) => {
  const { post, author } = props;
  return (
    <div
      className="flex w-full gap-2 border-b border-slate-400 p-4 "
      key={post.id}
    >
      <Image
        className="h-14 w-14 rounded-full"
        src={author.profileImageUrl}
        alt={`@${author.userName}'s profile image`}
        width={56}
        height={56}
        priority
      />
      <div className="flex grow flex-col">
        <p className="text-slate-500">
          @{author.userName}
          {" · "}
          <span className="opacity-50">{dayjs(post.createdAt).fromNow()}</span>
        </p>
        <p>{post.content}</p>
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  const { isSignedIn } = useUser();

  // start fetching posts asap
  api.post.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Chirp - Twitter clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center px-1 md:px-0">
        <div className="min-h-screen w-full max-w-3xl border-x border-slate-400">
          <div className="border-b border-slate-400 p-4">
            {isSignedIn && <CreatePostWizard />}
            {!isSignedIn && <SignInButton />}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
