import { SignOutButton } from "@clerk/clerk-react";
import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.post.getAll.useQuery();

  const user = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid min-h-[100vh] place-items-center">
        {/* header */}
        <div>{!!user.isSignedIn && <SignOutButton />}</div>

        {data?.map((post) => (
          <div key={post.id}>{post.content}</div>
        ))}
      </main>
    </>
  );
};

export default Home;
